// <auto-generated />
using Maruko.Permission.Core.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maruko.Permission.Core.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Maruko.Permission.Core.Domain.Permissions.MkoMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Icon");

                    b.Property<sbyte>("Level")
                        .HasColumnType("tinyint(4)");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Operates")
                        .HasMaxLength(100);

                    b.Property<int>("ParentId");

                    b.Property<int>("Sort");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("sys_menu");
                });

            modelBuilder.Entity("Maruko.Permission.Core.Domain.Permissions.MkoOperate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Remark")
                        .HasMaxLength(2147483647);

                    b.Property<int>("Unique");

                    b.HasKey("Id");

                    b.ToTable("sys_operate");
                });

            modelBuilder.Entity("Maruko.Permission.Core.Domain.Permissions.MkoRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Remark")
                        .HasMaxLength(2147483647);

                    b.HasKey("Id");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("Maruko.Permission.Core.Domain.Permissions.MkoRoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MenuId");

                    b.Property<string>("Operates")
                        .HasMaxLength(200);

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("sys_rolemenu");
                });

            modelBuilder.Entity("Maruko.Permission.Core.Domain.Permissions.MkoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("RoleId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });
#pragma warning restore 612, 618
        }
    }
}
